name: biobb_Protein-Complex_MDsetup_tutorial
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - biobb_common==2.0.1
  - biobb_analysis==2.0.3
  - biobb_io==2.0.1
  - biobb_model==2.0.0
  - biobb_md==2.0.0
  - biobb_chemistry==2.0.2
  - biobb_structure_utils==2.0.0
  - plotly
  - nglview
  - simpletraj
  - conda