name: biobb_wf_protein-complex_md_setup_tutorial
channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.6
  - biobb_analysis==1.0.5 
  - biobb_common==1.1.6
  - biobb_io==1.1.6
  - biobb_model==1.1.9
  - biobb_md==1.1.7
  - biobb_chemistry==1.0.8
  - biobb_structure_utils==2.0.0
  - plotly
  - nglview
  - simpletraj
  - conda