name: biobb_wf_protein-complex_md_setup
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - biobb_analysis==5.2.1
  - biobb_io==5.2.3
  - biobb_model==5.2.1
  - biobb_gromacs==5.2.1
  - biobb_chemistry==5.2.1
  - biobb_structure_utils==5.2.1
  - plotly
  - jupyterlab=3.6
  - nodejs=16
  - ipywidgets=7
  - nglview
  - simpletraj