name: biobb_Protein-Complex_MDsetup_tutorial
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_analysis==3.8.0
  - biobb_io==3.8.0
  - biobb_model==3.8.0
  - biobb_gromacs==3.8.0
  - biobb_chemistry==3.8.0
  - biobb_structure_utils==3.8.0
  - ipywidgets==7.6.6
  - jupyter_contrib_nbextensions
  - plotly
  - nglview
  - simpletraj
  - conda